#+title: An Overview of the Federal Reserve System
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
#+PROPERTY: header-args    :exports none

In these notes we'll cover the Federal Reserve System (hereafter 'the Fed') paying particular attention to its role in monetary policy and the regulation of financial institutions.

* A Brief History[^1] of the Fed

The Fed was created in 1913 with the passing of the Federal Reserve Act.  The creation of the Fed (a central bank for the US) was not without opponents.  See this paper for arguments against the Fed (TODO: cite). 

** The Gold Standard

An important point about the creation of the Fed, which is usually omitted, is that the Fed was created when the US was on the gold standard.  This means the Fed is fundamentally different than it is today.  When the Fed was created it could not simply print more money---if it wanted to issue a dollar it had to obtain the equivalent of gold.  Today, the Fed can simply create money from nothing.  The importance of distinction cannot be overstated.

So the Fed as it is really only dates to the 1970s (when we left the gold standard).  The Fed which started in 1913 is an entirely different organization---only with the same name.

* Fed Structure

The Fed is comprised of 5 subdivisions:

1.  Board of Governors
2.  Federal Open Market Committee
3.  Fed District Banks
4.  Advisory Committees
5.  Member Banks (commercial banks)

** Board of Governors

Comprised of 7 members appointed by POTUS (confirmed by Congress) for 14-year non-renewable terms.  One member is appointed by POTUS to be the Chairperson (again confirmed by Congress).  The Chairperson has no more vote than the other members.  The Board oversees the dual roles of the Fed (1) implement monetary policy and (2) to regulate commercial banks.





[^1]: While not intended to be, the Fed is unfortunately a political institution.  Stated simply, the Fed enables political policies.  This means any history of the Fed tends to be biased in accordance with the author's political opinions.
