#+title: An Overview of the Federal Reserve System
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
#+PROPERTY: header-args    :exports none

In these notes we'll cover the Federal Reserve System (hereafter 'the Fed') paying particular attention to its role in monetary policy and the regulation of financial institutions.

* A Brief History[fn:2] of the Fed

The Fed was created in 1913 with the passing of the Federal Reserve Act.  The creation of the Fed (a central bank for the US) was not without opponents.  See this paper for arguments against the Fed (TODO: cite). 

** The Gold Standard

An important point about the creation of the Fed, which is usually omitted, is that the Fed was created when the US was on the gold standard.  This means the Fed is fundamentally different than it is today.  When the Fed was created it could not simply print more money---if it wanted to issue a dollar it had to obtain the equivalent of gold.  Today, the Fed can simply create money from nothing.  The importance of distinction cannot be overstated.

So the Fed as it is really only dates to the 1970s (when we left the gold standard).  The Fed which started in 1913 is an entirely different organization---only with the same name.

* Fed Structure

The Fed is comprised of 5 subdivisions:

1.  Board of Governors
2.  Fed District Banks
3.  Federal Open Market Committee (FOMC)
4.  Advisory Committees
5.  Member Banks (commercial banks)

** Board of Governors (BOG)

Comprised of 7 members appointed by POTUS (confirmed by Congress) for 14-year non-renewable terms.  One member is appointed by POTUS to be the Chairperson (again confirmed by Congress).  The Chairperson has no more vote than the other members.  The Board oversees the dual roles of the Fed (1) implement monetary policy and (2) to regulate commercial banks.

** Fed District Banks

There are 12 district banks across the US.  [[https://www.stlouisfed.org/about-us/federal-reserve-map][See the interactive map here with links to each district bank.]] The district Fed banks are responsible for reporting the economic conditions in their district, as well as clearing checks, and offering loans to regional depository institutions through the discount window.

Notably, when a commercial bank becomes a member of the Fed system, it has to purchase stock in its Fed district bank.  This stock is not publicly traded.  So the Fed district bank are owned by commercial banks.

Each district bank is overseen by 9 directors---three appointed by the BOG, and 6 by member banks.  The 9 directors elect a president of the Fed district bank.

** FOMC

The FOMC is tasked[fn:1] by [[https://www.federalreserve.gov/monetarypolicy/files/fomc_longerrungoals.pdf][Congress with "promoting maximum employment, stable prices, and moderate long-term interest rates".]]  It does so through the use of open market operations, the discount rate, and reserve requirement (now set to 0%). 

The composition of the FOMC is:

- seven members of the BOG
- the president of the NY district bank (because NY implements monetary policy)
- presidents of 4 other district banks.  These president rotate on and off the committee.

** Advisory Committees

The Fed creates various advisory committees which we won't discuss here.  They may change over time.  [[https://www.federalreserve.gov/aboutthefed/advisorydefault.htm][Here is a present list.]]

* Monetary Policy

/Monetary Policy/ refers to control over the money supply. There are different measures of money supply, but here we can use the term to simply refer to the amount of money in the economy (leaving strict definitions of /money/ until later).

The Fed changes the money supply in order to affect the real economy[fn:3].  The effect on interest rates and asset prices is a means to an end---real economic growth.

** Outline of the Monetary Policy Process

Remember, the FOMC is the Fed committee which controls monetary policy.  The FOMC is scheduled to meet 8 times per year, however it can schedule additional meeting if needed (though this would only be done for extreme market conditions).

** Reserve Requirement Ratio

If you look in most textbooks, it will likely list adjusting the reserve requirement ratio as one of the tools the Fed has to adjust the money supply. There is also a discussion of the /money multiplier/.

[[https://www.federalreserve.gov/monetarypolicy/reservereq.htm][However, on March 15, 2020 the Fed Board of Governors announced that they were setting the reserve requirement ratio to 0%, thereby eliminating reserve requirements for all depository institutions.]]



* Footnotes

[fn:3]Note many economists think this is not possible---see Milton Friedman. 
[fn:2] While not intended to be, the Fed is unfortunately a political institution.  Stated simply, the Fed enables political policies.  This means any history of the Fed tends to be biased in accordance with the author's political opinions. 

[fn:1] Do you see a contradiction in the following goals? 
