#+title: An Overview of the Federal Reserve System
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <style>pre.src{background:#343131;color:white;} </style>
#+PROPERTY: header-args    :exports none

In these notes we'll cover the Federal Reserve System (hereafter 'the Fed') paying particular attention to its role in monetary policy and the regulation of financial institutions.

* A Brief History[fn:2] of the Fed

The Fed was created in 1913 with the passing of the Federal Reserve Act.  The creation of the Fed (a central bank for the US) was not without opponents.  See this paper for arguments against the Fed (TODO: cite). 

** The Gold Standard

An important point about the creation of the Fed, which is usually omitted, is that the Fed was created when the US was on the gold standard.  This means the Fed is fundamentally different than it is today.  When the Fed was created it could not simply print more money---if it wanted to issue a dollar it had to obtain the equivalent of gold.  Today, the Fed can simply create money from nothing.  The importance of distinction cannot be overstated.

So the Fed as it is really only dates to the 1970s (when we left the gold standard).  The Fed which started in 1913 is an entirely different organization---only with the same name.

* Fed Structure

The Fed is comprised of 5 subdivisions:

1.  Board of Governors
2.  Fed District Banks
3.  Federal Open Market Committee (FOMC)
4.  Advisory Committees
5.  Member Banks (commercial banks)

** Board of Governors (BOG)

Comprised of 7 members appointed by POTUS (confirmed by Congress) for 14-year non-renewable terms.  One member is appointed by POTUS to be the Chairperson (again confirmed by Congress).  The Chairperson has no more vote than the other members.  The Board oversees the dual roles of the Fed (1) implement monetary policy and (2) to regulate commercial banks.

** Fed District Banks

There are 12 district banks across the US.  [[https://www.stlouisfed.org/about-us/federal-reserve-map][See the interactive map here with links to each district bank.]] The district Fed banks are responsible for reporting the economic conditions in their district, as well as clearing checks, and offering loans to regional depository institutions through the discount window.

Notably, when a commercial bank becomes a member of the Fed system, it has to purchase stock in its Fed district bank.  This stock is not publicly traded.  So the Fed district bank are owned by commercial banks.

Each district bank is overseen by 9 directors---three appointed by the BOG, and 6 by member banks.  The 9 directors elect a president of the Fed district bank.

** FOMC

The FOMC is tasked[fn:1] by [[https://www.federalreserve.gov/monetarypolicy/files/fomc_longerrungoals.pdf][Congress with "promoting maximum employment, stable prices, and moderate long-term interest rates".]]  It does so through the use of open market operations, the discount rate, and reserve requirement (now set to 0%). 

The composition of the FOMC is:

- seven members of the BOG
- the president of the NY district bank (because NY implements monetary policy)
- presidents of 4 other district banks.  These president rotate on and off the committee.

** Advisory Committees

The Fed creates various advisory committees which we won't discuss here.  They may change over time.  [[https://www.federalreserve.gov/aboutthefed/advisorydefault.htm][Here is a present list.]]

* Monetary Policy

/Monetary Policy/ refers to control over the money supply. There are different measures of money supply, but here we can use the term to simply refer to the amount of money in the economy (leaving strict definitions of /money/ until later).

The Fed changes the money supply in order to affect the real economy[fn:3].  The effect on interest rates and asset prices is a means to an end---real economic growth.

** Outline of the Monetary Policy Process

Remember, the FOMC is the Fed committee which controls monetary policy.  The FOMC is scheduled to meet 8 times per year, however it can schedule additional meeting if needed (though this would only be done for extreme market conditions).  Prior to each meeting economic reports are prepared.  The FOMC has to know about the economic conditions around the country before it can decide on a monetary policy path.

** The Decision

At each meeting these economic reports are presented.  From these FOMC decision makers attempt to forecast likely path for inflation and economic growth.  Each FOMC member then has an opportunity to share their view on what actions should be taken.  The FOMC members then vote on the potential actions to be taken---usually on the target federal funds rate.  Very often, the vote is unanimous.  This latter point is deemed important because the Fed relies on the confidence of market participants to successfully implment its monetary policy.

** Open Market Operations (the Implementation)

Say for example, the FOMC decides to raise the Federal Funds rate[fn:4] from 5.0% to 5.25%.  The Fed can't simply mandate that banks lend to each other at this rate.  The Fed must change the supply of funds, thereby affecting the Federal Funds rate.  So management of the /target/ Federal Funds is a constant process. See the chart below of the /effective/ Federal Funds rate.  The rate deviates from the target by small amounts. You may have to zoom in a bit to see the deviations.

#+begin_export html
<iframe src="https://fred.stlouisfed.org/graph/graph-landing.php?g=1fshl&width=670&height=475" scrolling="no" frameborder="0" style="overflow:hidden; width:670px; height:525px;" allowTransparency="true" loading="lazy"></iframe>
#+end_export

To change the supply of funds, the Fed trading desk (at the NY Fed) conducts /open market operations/.  If the Fed wants to raise the Federal funds rate (as in our example) it sells securities.  This sale decreases the money supply, which raises the value of money (the interest rate).  If instead the Fed wanted to lower the Federal Funds rate it would have bought securities, which increases the money supply and lowers interest rates.

#+begin_quote
When you buy or sell securities the money supply doesn't change.  Why does the money supply change when the Fed buys or sells securities?

The key is the Fed is the source of money; it can't have any more or less.  So when the Fed buys securities it creates money and credits the sellers account. Alternatively when the Fed buys securities it receives money, which goes away as the Fed's accounts can't have more money.
#+end_quote

#+caption: Open-Market Operations Summary
|------------------+------------------------+--------------------------|
| Fed Action       | Effect in Money Supply | Effect on Fed Funds Rate |
|------------------+------------------------+--------------------------|
| Buys Securities  | Increases              | Decreases                |
| Sells Securities | Decreases              | Increases                |
|------------------+------------------------+--------------------------|


*** The Discount Rate

If member banks borrow directly from the Fed, they borrow at the /discount window/.  The rate at which they borrow is the /discount rate/.  Historically (pre 2008) the discount window was used infrequently, however as the banking sector has experienced a series of crises the discount window has become more important.

https://www.federalreserve.gov/monetarypolicy/discountrate.htm

*** Do OMO Only Affect Short-Term Rates?

Historically the FOMC has only adjusted the Federal Funds rate via OMO, which is an over night rate (thus very short-term).  Adjusting the overnight rate can have an effect across the yield curve in a number of ways. First, if the market believes the Fed will keep the overnight rate at some level for a year, then by pure expectations this should be the one year interest rate.

Also, by increasing the supply of federal funds, the Fed increases the propensity of banks to lend.  Thus, banks transfer the excess supply of funds at the overnight rate to an increased supply of loans across the yield curve, lowering longer term rates and increasing economic growth.  Conversely recusing the amount of federal funds lowers the amount of funds banks have to lend long term, which raising interest rates along the curve and slows economic growth.

*Directly Affecting Long-term Rates*

Since 2008 however the Fed has used open market operations (the buying and selling of marketable securities) buy longer dated securities.  Moreover, the Fed bought non-Treasury issued securities such as mortgage-backed securities (MBS).  The term the Fed used for this is /Quantitative Easing/ (QE).  See the description[fn:5] of [[https://en.wikipedia.org/wiki/Quantitative_easing][Quantitative Easing here]].  Be sure to scroll down to see the various iterations of QE.

** Reserve Requirement Ratio

If you look in most textbooks, it will likely list adjusting the reserve requirement ratio as one of the tools the Fed has to adjust the money supply. There is also a discussion of the /money multiplier/.

[[https://www.federalreserve.gov/monetarypolicy/reservereq.htm][However, on March 15, 2020 the Fed Board of Governors announced that they were setting the reserve requirement ratio to 0%, thereby eliminating reserve requirements for all depository institutions.]]



* Footnotes

[fn:5]Normally I don't disagree with Wikipedia, however its description of QE as "a novel form of monetary policy" is inaccurate.  QE prints money to buy long-term securities.  Printing money has existed throughout history, and using this money to buy mortgages instead of land itself, as ancient Rome did when debasing its currency, seems to be a somewhat artificial distinction.
[fn:4]The Federal Funds rate is the rate at which bank's borrow and lend federal funds to eachother.  It is an overnight rate.  Federal funds are funds banks must hold at the Federal reserve. 

[fn:3]Note many economists think this is not possible---see Milton Friedman. 
[fn:2] While not intended to be, the Fed is unfortunately a political institution.  Stated simply, the Fed enables political policies.  This means any history of the Fed tends to be biased in accordance with the author's political opinions. 

[fn:1] Do you see a contradiction in the following goals? 
